service: nodeless

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:lambda:us-east-1:"
            - Ref: AWS::AccountId
            - ":function:nodeless-dev-channel"

functions:
  channel:
    handler: index.handle
    timeout: 10
    environment:
      bucket: youtube-redes2
