service: nodeless

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
      Resource:
        - "arn:aws:s3:::*"
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - "arn:aws:s3:::*"

functions:
  channel:
    handler: index.handle
    timeout: 5
    environment:
      bucket: youtube-redes
